import { describe, expect, it } from "vitest";
import {
  CoreError,
  GameService,
  InMemoryGameRepository,
  PlayerViewService,
  InMemoryDurableGameStore,
  DurableGameService,
  projectPlayerView,
  projectPublicView,
  replay,
  supportedRulesetSnapshot,
  type ClockPort,
  type Command,
  type GameState,
  type IdPort,
  type RandomPort,
  type Seat,
} from "../../src/index.js";

class FixedClock implements ClockPort { nowIso(): string { return "2026-09-19T11:00:00.000Z"; } }
class CountingIds implements IdPort { calls = 0; constructor(readonly prefix = "b-id") {} nextId(): string { this.calls += 1; return `${this.prefix}-${this.calls}`; } }
class FixedRandom implements RandomPort {
  readonly algorithmId = "test.fixed";
  readonly privateSeed: string | null = "test-only-seed";
  calls = 0;
  constructor(readonly values: number[] = [0, 1, 2, 3]) {}
  randomInt(exclusiveUpperBound: number): number { const value = this.values[this.calls % this.values.length] ?? 0; this.calls += 1; return value % exclusiveUpperBound; }
}
const host = { kind: "HOST", hostId: "host-1" } as const;
const principal = (playerId: string) => ({ kind: "PLAYER", playerId }) as const;
const seats = (): Seat[] => Array.from({ length: 12 }, (_, index) => ({ playerId: `player-${index + 1}`, seatNumber: index + 1, displayName: `Player ${index + 1}`, controllerType: index === 0 ? "HUMAN" as const : "NPC" as const }));

function command(gameId: string, type: "CreateGame" | "ConfigureSeats" | "LockGame" | "StartGame", id: string): Command {
  if (type === "CreateGame") return { commandId: id, gameId, actorPlayerId: null, commandType: type, payload: { rulesetSnapshot: supportedRulesetSnapshot() }, windowToken: null };
  if (type === "ConfigureSeats") return { commandId: id, gameId, actorPlayerId: null, commandType: type, payload: { seats: seats() }, windowToken: null };
  return { commandId: id, gameId, actorPlayerId: null, commandType: type, payload: {}, windowToken: null };
}

function harness(gameId: string, started = true) {
  const repository = new InMemoryGameRepository();
  const service = new GameService({ repository, clock: new FixedClock(), ids: new CountingIds(), random: new FixedRandom(), engineBuildId: "b-test" });
  service.handle(host, command(gameId, "CreateGame", `${gameId}-create`));
  service.handle(host, command(gameId, "ConfigureSeats", `${gameId}-seats`));
  service.handle(host, command(gameId, "LockGame", `${gameId}-lock`));
  if (started) service.handle(host, command(gameId, "StartGame", `${gameId}-start`));
  return { gameId, repository, service };
}
function stateOf(h: ReturnType<typeof harness>): GameState { const state = replay(h.repository.loadEvents(h.gameId)); if (state === null) throw new Error("missing state"); return state; }
function role(h: ReturnType<typeof harness>, roleId: string): string { const id = stateOf(h).lockedSetup?.assignments.find((entry) => entry.assignedRoleId === roleId)?.playerId; if (id === undefined) throw new Error(`missing ${roleId}`); return id; }
function rolePlayers(h: ReturnType<typeof harness>, roleId: string): string[] { return stateOf(h).lockedSetup?.assignments.filter((entry) => entry.assignedRoleId === roleId).map((entry) => entry.playerId) ?? []; }
function wolves(h: ReturnType<typeof harness>): string[] { return stateOf(h).lockedSetup?.assignments.filter((entry) => entry.assignedFactionId === "WOLF").map((entry) => entry.playerId) ?? []; }
function nightToken(h: ReturnType<typeof harness>): string { const token = stateOf(h).runtime?.nightSession.currentActionSession?.sessionId; if (token === undefined) throw new Error("missing night token"); return token; }
function send(h: ReturnType<typeof harness>, actorPlayerId: string, value: Omit<Extract<Command, { actorPlayerId: string }>, "gameId" | "actorPlayerId">): void { h.service.handle(principal(actorPlayerId), { ...value, gameId: h.gameId, actorPlayerId } as Command); }
function guardPass(h: ReturnType<typeof harness>): void { const actor = role(h, "GUARD"); send(h, actor, { commandId: `${h.gameId}-guard-${stateOf(h).runtime?.round}`, commandType: "CommitGuardAction", payload: { targetPlayerId: null }, windowToken: nightToken(h) }); }
function wolfVoteAll(h: ReturnType<typeof harness>, targets: readonly (string | null)[]): void { for (const [index, actor] of wolves(h).filter((id) => stateOf(h).runtime?.players.find((p) => p.playerId === id)?.lifeState === "ALIVE").entries()) send(h, actor, { commandId: `${h.gameId}-wolf-${stateOf(h).runtime?.round}-${index}`, commandType: "CommitWolfBallot", payload: { targetPlayerId: targets[index] ?? null }, windowToken: nightToken(h) }); }
function beauty(h: ReturnType<typeof harness>, target: string | null = null): void { const actor = role(h, "WOLF_BEAUTY"); if (stateOf(h).runtime?.players.find((p) => p.playerId === actor)?.lifeState !== "ALIVE") return; send(h, actor, target === null ? { commandId: `${h.gameId}-beauty-${stateOf(h).runtime?.round}`, commandType: "CommitBeautyAction", payload: { mode: "KEEP", targetPlayerId: null }, windowToken: nightToken(h) } : { commandId: `${h.gameId}-beauty-${stateOf(h).runtime?.round}`, commandType: "CommitBeautyAction", payload: { mode: "CHARM", targetPlayerId: target }, windowToken: nightToken(h) }); }
function witch(h: ReturnType<typeof harness>, action: "PASS" | "HEAL" | "POISON", target: string | null): void { const actor = role(h, "WITCH"); if (stateOf(h).runtime?.players.find((p) => p.playerId === actor)?.lifeState !== "ALIVE") return; send(h, actor, action === "PASS" ? { commandId: `${h.gameId}-witch-${stateOf(h).runtime?.round}`, commandType: "CommitWitchAction", payload: { action, targetPlayerId: null }, windowToken: nightToken(h) } : { commandId: `${h.gameId}-witch-${stateOf(h).runtime?.round}`, commandType: "CommitWitchAction", payload: { action, targetPlayerId: target! }, windowToken: nightToken(h) }); }
function seer(h: ReturnType<typeof harness>, target: string | null): void { const actor = role(h, "SEER"); if (stateOf(h).runtime?.players.find((p) => p.playerId === actor)?.lifeState !== "ALIVE") return; send(h, actor, { commandId: `${h.gameId}-seer-${stateOf(h).runtime?.round}`, commandType: "CommitSeerAction", payload: { targetPlayerId: target }, windowToken: nightToken(h) }); }
function resolveNight(h: ReturnType<typeof harness>): void { const round = stateOf(h).runtime?.round ?? 1; h.service.handle(host, { commandId: `${h.gameId}-resolve-${round}`, gameId: h.gameId, actorPlayerId: null, commandType: "ResolveNight", payload: {}, windowToken: null }); }
function beginDay(h: ReturnType<typeof harness>): void { const round = stateOf(h).runtime?.round ?? 1; h.service.handle(host, { commandId: `${h.gameId}-day-${round}`, gameId: h.gameId, actorPlayerId: null, commandType: "BeginDay", payload: {}, windowToken: null }); }
function finishSpeech(h: ReturnType<typeof harness>, prefix: string): void { const session = stateOf(h).runtime?.speechSession; if (session === null || session === undefined) throw new Error("speech"); for (const speaker of session.speakerOrderSnapshot.slice(session.completedSpeakers.length)) send(h, speaker, { commandId: `${prefix}-${speaker}`, commandType: "CommitSpeech", payload: { mode: "PASS", text: null, source: null }, windowToken: session.sessionId }); }
function noSheriff(h: ReturnType<typeof harness>): void { const session = stateOf(h).runtime?.sheriff.signupSession; if (session === null || session === undefined) throw new Error("signup"); for (const actor of session.eligiblePlayersSnapshot) send(h, actor, { commandId: `${h.gameId}-signup-${actor}`, commandType: "CommitSheriffSignup", payload: { join: false }, windowToken: session.sessionId }); }
function vote(h: ReturnType<typeof harness>, target: string | null, count?: number): void { const session = stateOf(h).runtime?.voteSession; if (session === null || session === undefined) throw new Error("vote"); for (const actor of session.eligibleVotersSnapshot.slice(0, count ?? session.eligibleVotersSnapshot.length)) send(h, actor, { commandId: `${h.gameId}-vote-${session.roundIndex}-${actor}`, commandType: "CommitBallot", payload: { targetPlayerId: target }, windowToken: session.sessionId }); }
function peacefulFirstNight(h: ReturnType<typeof harness>): void { guardPass(h); wolfVoteAll(h, wolves(h).map(() => null)); beauty(h); witch(h, "PASS", null); seer(h, null); resolveNight(h); }
function allKeys(value: unknown, out = new Set<string>()): Set<string> { if (Array.isArray(value)) for (const item of value) allKeys(item, out); else if (value !== null && typeof value === "object") for (const [key, child] of Object.entries(value as Record<string, unknown>)) { out.add(key); allKeys(child, out); } return out; }
function expectCoreError(fn: () => unknown, code: CoreError["code"]): void { try { fn(); throw new Error("expected CoreError"); } catch (error: unknown) { expect(error).toBeInstanceOf(CoreError); expect((error as CoreError).code).toBe(code); } }

describe("B Player View projection and information isolation", () => {
  it("B-01 public locked view exposes board configuration but no role assignments or seed", () => { const h = harness("b-locked", false); const view = projectPublicView(h.repository.loadEvents(h.gameId)); const keys = allKeys(view); expect(view.stage.kind).toBe("LOCKED"); expect(view.ruleset.roles.reduce((sum, entry) => sum + entry.count, 0)).toBe(12); expect(keys.has("assignments")).toBe(false); expect(keys.has("privateSeed")).toBe(false); expect(keys.has("assignedRoleId")).toBe(false); });
  it("B-02 each seated player receives only their own locked identity", () => { const h = harness("b-self", false); const villager = rolePlayers(h, "VILLAGER")[0]!; const view = projectPlayerView(h.repository.loadEvents(h.gameId), villager); expect(view.identity?.playerId).toBe(villager); expect(view.identity?.roleId).toBe("VILLAGER"); expect(view.identity?.initiallyKnownIdentities).toEqual([]); });
  it("B-03 wolves know their wolf teammates including the special role; good roles do not", () => { const h = harness("b-wolf-knowledge", false); const wolf = rolePlayers(h, "WEREWOLF")[0]!; const wolfView = projectPlayerView(h.repository.loadEvents(h.gameId), wolf); const team = wolfView.identity?.initiallyKnownIdentities ?? []; expect(team).toHaveLength(3); expect(team.some((entry) => entry.roleId === "WOLF_BEAUTY")).toBe(true); const seerView = projectPlayerView(h.repository.loadEvents(h.gameId), role(h, "SEER")); expect(seerView.identity?.initiallyKnownIdentities).toEqual([]); });
  it("B-04 non-seated viewer is rejected", () => { const h = harness("b-outsider", false); expectCoreError(() => projectPlayerView(h.repository.loadEvents(h.gameId), "outsider"), "UNAUTHORIZED"); });
  it("B-05 night public stage hides role-specific phase while only guard receives guard window token", () => { const h = harness("b-night-hide"); const guard = role(h, "GUARD"); const villager = rolePlayers(h, "VILLAGER")[0]!; const publicView = projectPublicView(h.repository.loadEvents(h.gameId)); expect(publicView.stage.kind).toBe("NIGHT"); expect(publicView.currentTurn.kind).toBe("NONE"); expect(JSON.stringify(publicView)).not.toContain(nightToken(h)); expect(projectPlayerView(h.repository.loadEvents(h.gameId), guard).availableActions[0]?.commandType).toBe("CommitGuardAction"); expect(projectPlayerView(h.repository.loadEvents(h.gameId), villager).availableActions).toEqual([]); });
  it("B-06 committed wolf sees submitted state and final wolf target is private only to eligible wolves", () => { const h = harness("b-wolf-target"); guardPass(h); const [w1, w2, w3, w4] = wolves(h); const target = role(h, "SEER"); send(h, w1!, { commandId: "w1", commandType: "CommitWolfBallot", payload: { targetPlayerId: target }, windowToken: nightToken(h) }); expect(projectPlayerView(h.repository.loadEvents(h.gameId), w1!).interactionStatus).toBe("ACTION_SUBMITTED"); for (const [index, wolf] of [w2!, w3!, w4!].entries()) send(h, wolf, { commandId: `wr-${index}`, commandType: "CommitWolfBallot", payload: { targetPlayerId: target }, windowToken: nightToken(h) }); for (const wolf of wolves(h)) expect(projectPlayerView(h.repository.loadEvents(h.gameId), wolf).privateObservations.some((entry) => entry.type === "WOLF_TARGET" && entry.targetPlayerId === target)).toBe(true); expect(projectPlayerView(h.repository.loadEvents(h.gameId), role(h, "WITCH")).privateObservations.some((entry) => entry.type === "WOLF_TARGET")).toBe(false); });
  it("B-07 witch gets TARGET knife information only when her window opens and heal remains", () => { const h = harness("b-witch-info"); guardPass(h); const target = role(h, "SEER"); wolfVoteAll(h, wolves(h).map(() => target)); beauty(h); const witchId = role(h, "WITCH"); const witchView = projectPlayerView(h.repository.loadEvents(h.gameId), witchId); expect(witchView.privateObservations.at(-1)).toMatchObject({ type: "WITCH_KNIFE_INFO", status: "TARGET", targetPlayerId: target }); expect(witchView.availableActions[0]).toMatchObject({ commandType: "CommitWitchAction", knifeInfo: { status: "TARGET", targetPlayerId: target }, healTargetPlayerId: target }); const villager = projectPlayerView(h.repository.loadEvents(h.gameId), rolePlayers(h, "VILLAGER")[0]!); expect(villager.privateObservations.some((entry) => entry.type === "WITCH_KNIFE_INFO")).toBe(false); });
  it("B-08 tied wolf vote becomes private NO_ATTACK for witch instead of UNAVAILABLE", () => { const h = harness("b-witch-no-attack"); guardPass(h); const [a, b] = rolePlayers(h, "VILLAGER"); wolfVoteAll(h, [a!, a!, b!, b!]); beauty(h); const view = projectPlayerView(h.repository.loadEvents(h.gameId), role(h, "WITCH")); expect(view.privateObservations.at(-1)).toMatchObject({ type: "WITCH_KNIFE_INFO", status: "NO_ATTACK", targetPlayerId: null }); });
  it("B-09 seer check result is delivered to seer and not to target or unrelated player", () => { const h = harness("b-seer-private"); guardPass(h); wolfVoteAll(h, wolves(h).map(() => null)); beauty(h); witch(h, "PASS", null); const seerId = role(h, "SEER"); const target = wolves(h)[0]!; seer(h, target); resolveNight(h); expect(projectPlayerView(h.repository.loadEvents(h.gameId), seerId).privateObservations).toContainEqual(expect.objectContaining({ type: "SEER_CHECK", targetPlayerId: target, result: "WOLF" })); expect(projectPlayerView(h.repository.loadEvents(h.gameId), target).privateObservations.some((entry) => entry.type === "SEER_CHECK")).toBe(false); expect(projectPlayerView(h.repository.loadEvents(h.gameId), rolePlayers(h, "VILLAGER")[0]!).privateObservations.some((entry) => entry.type === "SEER_CHECK")).toBe(false); });
  it("B-10 player view never exposes raw event envelope/debug keys", () => { const h = harness("b-raw-keys"); const view = projectPlayerView(h.repository.loadEvents(h.gameId), rolePlayers(h, "VILLAGER")[0]!); const keys = allKeys(view); for (const forbidden of ["eventId", "sequence", "transactionId", "causationCommandId", "causedByEventIds", "phaseId", "recordedAtIso", "audience", "privateSeed", "sourceEffectIds", "deathEventSequence", "lastSequence"]) expect(keys.has(forbidden)).toBe(false); });
  it("B-11 night death remains publicly ALIVE before DawnAnnouncement and becomes DEAD only at dawn", () => { const h = harness("b-dawn-gate"); const target = rolePlayers(h, "VILLAGER")[0]!; guardPass(h); wolfVoteAll(h, wolves(h).map(() => target)); beauty(h); witch(h, "PASS", null); seer(h, null); resolveNight(h); const events = h.repository.loadEvents(h.gameId); const dawnIndex = events.findIndex((event) => event.eventType === "DawnAnnouncementPublished"); expect(dawnIndex > 0).toBe(true); const beforeDawn = projectPublicView(events.slice(0, dawnIndex)); expect(beforeDawn.seats.find((seat) => seat.playerId === target)?.lifeState).toBe("ALIVE"); const afterDawn = projectPublicView(events.slice(0, dawnIndex + 1)); expect(afterDawn.seats.find((seat) => seat.playerId === target)?.lifeState).toBe("DEAD"); });
  it("B-12 dawn observation publishes only dead roster, not night death causes", () => { const h = harness("b-dawn-cause"); const target = rolePlayers(h, "VILLAGER")[0]!; guardPass(h); wolfVoteAll(h, wolves(h).map(() => target)); beauty(h); witch(h, "PASS", null); seer(h, null); resolveNight(h); const text = JSON.stringify(projectPublicView(h.repository.loadEvents(h.gameId))); expect(text).toContain(target); expect(text).not.toContain("WEREWOLF_ATTACK"); expect(text).not.toContain("WITCH_POISON"); expect(text).not.toContain("GUARD_HEAL_COLLISION"); });
  it("B-13 partial vote exposes no partial ballot choices or committed count", () => { const h = harness("b-partial-vote"); peacefulFirstNight(h); beginDay(h); noSheriff(h); finishSpeech(h, "public-speech"); const session = stateOf(h).runtime?.voteSession; if (session === null || session === undefined) throw new Error("vote"); const first = session.eligibleVotersSnapshot[0]!; send(h, first, { commandId: "one-vote", commandType: "CommitBallot", payload: { targetPlayerId: session.eligibleTargetsSnapshot[0]! }, windowToken: session.sessionId }); const publicView = projectPublicView(h.repository.loadEvents(h.gameId)); expect(publicView.timeline.some((entry) => entry.type === "VOTE_RESULT")).toBe(false); expect(allKeys(publicView).has("ballots")).toBe(false); expect(allKeys(publicView).has("committedActors")).toBe(false); });
  it("B-14 resolved vote publishes full ballot result without committedAtSequence", () => { const h = harness("b-full-vote"); peacefulFirstNight(h); beginDay(h); noSheriff(h); finishSpeech(h, "speech"); const target = rolePlayers(h, "VILLAGER")[0]!; vote(h, target); const result = projectPublicView(h.repository.loadEvents(h.gameId)).timeline.find((entry) => entry.type === "VOTE_RESULT"); expect(result?.type === "VOTE_RESULT" ? result.ballots.length > 0 : false).toBe(true); expect(allKeys(result).has("committedAtSequence")).toBe(false); });
  it("B-15 published speech is visible verbatim and role claims do not alter identity", () => { const h = harness("b-speech"); peacefulFirstNight(h); beginDay(h); noSheriff(h); const session = stateOf(h).runtime?.speechSession; const speaker = session?.speakerOrderSnapshot[0]; if (session === null || session === undefined || speaker === undefined) throw new Error("speech"); const actualRole = stateOf(h).lockedSetup?.assignments.find((entry) => entry.playerId === speaker)?.assignedRoleId; send(h, speaker, { commandId: "speech-one", commandType: "CommitSpeech", payload: { mode: "SPEAK", text: "我是女巫", source: "HUMAN_TEXT" }, windowToken: session.sessionId }); const view = projectPublicView(h.repository.loadEvents(h.gameId)); expect(view.timeline).toContainEqual(expect.objectContaining({ type: "SPEECH", speakerPlayerId: speaker, text: "我是女巫" })); expect(stateOf(h).runtime?.players.find((entry) => entry.playerId === speaker)?.effectiveRoleId).toBe(actualRole); });
  it("B-16 public self explosion reveals death but no assignment fields", () => { const h = harness("b-boom"); peacefulFirstNight(h); beginDay(h); noSheriff(h); const wolf = wolves(h)[0]!; const session = stateOf(h).runtime?.speechSession; if (session === null || session === undefined) throw new Error("speech"); send(h, wolf, { commandId: "boom", commandType: "CommitSelfExplosion", payload: {}, windowToken: session.sessionId }); const publicView = projectPublicView(h.repository.loadEvents(h.gameId)); expect(publicView.timeline).toContainEqual(expect.objectContaining({ type: "SELF_EXPLOSION", playerId: wolf })); expect(publicView.seats.find((seat) => seat.playerId === wolf)?.lifeState).toBe("DEAD"); expect(allKeys(publicView).has("assignedRoleId")).toBe(false); });
  it("B-17 hidden-world swap among other players leaves a villager PlayerView identical", () => { const h = harness("b-indistinguishable", false); const events = h.repository.loadEvents(h.gameId); const state = stateOf(h); const viewer = rolePlayers(h, "VILLAGER")[0]!; const others = state.lockedSetup!.assignments.filter((entry) => entry.playerId !== viewer); const a = others.find((entry) => entry.assignedRoleId === "SEER")!; const b = others.find((entry) => entry.assignedRoleId === "WEREWOLF")!; const swapped = events.map((event) => { if (event.eventType !== "SetupLocked") return event; const assignments = event.payload.lockedSetup.assignments.map((entry) => entry.playerId === a.playerId ? { ...entry, assignedRoleId: b.assignedRoleId, assignedFactionId: b.assignedFactionId, victoryBucket: b.victoryBucket } : entry.playerId === b.playerId ? { ...entry, assignedRoleId: a.assignedRoleId, assignedFactionId: a.assignedFactionId, victoryBucket: a.victoryBucket } : entry); return { ...event, payload: { ...event.payload, lockedSetup: { ...event.payload.lockedSetup, assignments } } }; }); expect(projectPlayerView(swapped, viewer)).toEqual(projectPlayerView(events, viewer)); });
  it("B-18 after spending heal, next-night witch knife information is UNAVAILABLE even when wolves attack", () => { const h = harness("b-witch-spent"); const target = rolePlayers(h, "VILLAGER")[0]!; guardPass(h); wolfVoteAll(h, wolves(h).map(() => target)); beauty(h); witch(h, "HEAL", target); seer(h, null); resolveNight(h); beginDay(h); noSheriff(h); finishSpeech(h, "day1"); vote(h, null); expect(stateOf(h).runtime?.round).toBe(2); guardPass(h); const secondTarget = rolePlayers(h, "VILLAGER")[1]!; wolfVoteAll(h, wolves(h).map(() => secondTarget)); beauty(h); const witchId = role(h, "WITCH"); const view = projectPlayerView(h.repository.loadEvents(h.gameId), witchId); expect(view.privateObservations.at(-1)).toMatchObject({ type: "WITCH_KNIFE_INFO", nightNumber: 2, status: "UNAVAILABLE", targetPlayerId: null }); expect(view.availableActions[0]).toMatchObject({ commandType: "CommitWitchAction", knifeInfo: { status: "UNAVAILABLE", targetPlayerId: null }, healRemaining: 0 }); });
  it("B-19 a wolf killed on night one receives no new wolf target observation on night two", () => { const h = harness("b-dead-wolf"); const deadWolf = wolves(h).find((id) => stateOf(h).lockedSetup?.assignments.find((entry) => entry.playerId === id)?.assignedRoleId === "WEREWOLF")!; guardPass(h); wolfVoteAll(h, wolves(h).map(() => null)); beauty(h); witch(h, "POISON", deadWolf); seer(h, null); resolveNight(h); beginDay(h); if (stateOf(h).runtime?.phase?.phaseType === "LAST_WORDS") finishSpeech(h, "last"); noSheriff(h); finishSpeech(h, "day"); vote(h, null); expect(stateOf(h).runtime?.round).toBe(2); guardPass(h); const target = rolePlayers(h, "VILLAGER")[0]!; wolfVoteAll(h, wolves(h).map(() => target)); const view = projectPlayerView(h.repository.loadEvents(h.gameId), deadWolf); expect(view.privateObservations.filter((entry) => entry.type === "WOLF_TARGET").some((entry) => entry.nightNumber === 2)).toBe(false); expect(view.availableActions).toEqual([]); expect(view.interactionStatus).toBe("DEAD"); });
  it("B-20 public projection never exposes current window token", () => { const h = harness("b-public-token"); const token = nightToken(h); expect(JSON.stringify(projectPublicView(h.repository.loadEvents(h.gameId)))).not.toContain(token); });
  it("B-21 private observation ordinal is viewer-local rather than raw event sequence", () => { const h = harness("b-local-ordinal"); guardPass(h); wolfVoteAll(h, wolves(h).map(() => null)); beauty(h); witch(h, "PASS", null); const seerId = role(h, "SEER"); seer(h, wolves(h)[0]!); resolveNight(h); const checks = projectPlayerView(h.repository.loadEvents(h.gameId), seerId).privateObservations.filter((entry) => entry.type === "SEER_CHECK"); expect(checks).toHaveLength(1); expect(checks[0]?.ordinal).toBe(1); });
  it("B-22 Durable PlayerViewService reads through durable event truth", async () => { const store = new InMemoryDurableGameStore(); const service = new DurableGameService({ store, clock: new FixedClock(), ids: new CountingIds("durable"), random: new FixedRandom(), engineBuildId: "b-durable", snapshotEveryEvents: 0 }); const gameId = "b-durable"; await service.handle(host, command(gameId, "CreateGame", "d-create")); await service.handle(host, command(gameId, "ConfigureSeats", "d-seats")); await service.handle(host, command(gameId, "LockGame", "d-lock")); const events = await store.loadEvents(gameId); const state = replay(events); const viewer = state?.lockedSetup?.assignments.find((entry) => entry.assignedRoleId === "VILLAGER")?.playerId; if (viewer === undefined) throw new Error("viewer"); const viewService = new PlayerViewService(store); expect((await viewService.forPlayer(gameId, viewer)).identity?.roleId).toBe("VILLAGER"); expect((await viewService.publicView(gameId)).gameId).toBe(gameId); });
});
